@echo off
title Importing file associations into Windows image

set _file=install.wim
set _b64=associat.b64
set _xml=associat.xml
set _make=Commit
set _mnt=mount

dism /English /LogLevel:1 /Get-Help | find "Version: 6.1" > nul && exit

if not exist %_file% goto :decode
dism /English /LogLevel:1 /Get-ImageInfo /ImageFile:%_file%
echo -------------------------------------------------------------------------------
if %ERRORLEVEL% NEQ 0 pause & exit
set /p _ind=Input index or press [Enter] for quit: || exit

cls
dism /English /LogLevel:1 /Get-ImageInfo /ImageFile:%_file% /Index:%_ind%
echo -------------------------------------------------------------------------------
if %ERRORLEVEL% NEQ 0 pause & exit
choice /c abcdefghijklmnopqrstuvwxyz /n /m "Mount selected image? [m] "
if %ERRORLEVEL% NEQ 13 exit

cls
md %_mnt%
dism /English /LogLevel:1 /Mount-Image /ImageFile:%_file% /Index:%_ind% /MountDir:%_mnt%
if %ERRORLEVEL% NEQ 0 rd %_mnt% & pause & exit

:decode
(
echo PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxEZWZhdWx0
echo QXNzb2NpYXRpb25zPg0KICA8QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLjNnMiIg
echo UHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuM0cyIiBBcHBsaWNhdGlvbk5hbWU9Ildp
echo bmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRpb24gSWRlbnRpZmll
echo cj0iLjNncCIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuM0dQIiBBcHBsaWNhdGlv
echo bk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRpb24g
echo SWRlbnRpZmllcj0iLjNncDIiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLjNHMiIg
echo QXBwbGljYXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFz
echo c29jaWF0aW9uIElkZW50aWZpZXI9Ii4zZ3BwIiBQcm9nSWQ9IldNUDExLkFzc29j
echo RmlsZS4zR1AiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIi
echo IC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuYWFjIiBQcm9nSWQ9IldN
echo UDExLkFzc29jRmlsZS5BRFRTIiBBcHBsaWNhdGlvbk5hbWU9IldpbmRvd3MgTWVk
echo aWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLmFkdCIg
echo UHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuQURUUyIgQXBwbGljYXRpb25OYW1lPSJX
echo aW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZp
echo ZXI9Ii5hZHRzIiBQcm9nSWQ9IldNUDExLkFzc29jRmlsZS5BRFRTIiBBcHBsaWNh
echo dGlvbk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRp
echo b24gSWRlbnRpZmllcj0iLmF2aSIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuQVZJ
echo IiBBcHBsaWNhdGlvbk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8
echo QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLmJtcCIgUHJvZ0lkPSJQQnJ1c2giIEFw
echo cGxpY2F0aW9uTmFtZT0iUGFpbnQiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlm
echo aWVyPSIuZGliIiBQcm9nSWQ9IlBCcnVzaCIgQXBwbGljYXRpb25OYW1lPSJQYWlu
echo dCIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5mbGFjIiBQcm9nSWQ9
echo IldNUDExLkFzc29jRmlsZS5GTEFDIiBBcHBsaWNhdGlvbk5hbWU9IldpbmRvd3Mg
echo TWVkaWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLmdp
echo ZiIgUHJvZ0lkPSJQQnJ1c2giIEFwcGxpY2F0aW9uTmFtZT0iUGFpbnQiIC8+DQog
echo IDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuaHRtIiBQcm9nSWQ9IklFLkFzc29j
echo RmlsZS5IVE0iIEFwcGxpY2F0aW9uTmFtZT0iSW50ZXJuZXQgRXhwbG9yZXIiIC8+
echo DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuaHRtbCIgUHJvZ0lkPSJJRS5B
echo c3NvY0ZpbGUuSFRNIiBBcHBsaWNhdGlvbk5hbWU9IkludGVybmV0IEV4cGxvcmVy
echo IiAvPg0KICA8QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLmpmaWYiIFByb2dJZD0i
echo UEJydXNoIiBBcHBsaWNhdGlvbk5hbWU9IlBhaW50IiAvPg0KICA8QXNzb2NpYXRp
echo b24gSWRlbnRpZmllcj0iLmpwZSIgUHJvZ0lkPSJQQnJ1c2giIEFwcGxpY2F0aW9u
echo TmFtZT0iUGFpbnQiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuanBl
echo ZyIgUHJvZ0lkPSJQQnJ1c2giIEFwcGxpY2F0aW9uTmFtZT0iUGFpbnQiIC8+DQog
echo IDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuanBnIiBQcm9nSWQ9IlBCcnVzaCIg
echo QXBwbGljYXRpb25OYW1lPSJQYWludCIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50
echo aWZpZXI9Ii5tMnQiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLk0yVFMiIEFwcGxp
echo Y2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lh
echo dGlvbiBJZGVudGlmaWVyPSIubTJ0cyIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUu
echo TTJUUyIgQXBwbGljYXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4N
echo CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5tM3UiIFByb2dJZD0iV01QMTEu
echo QXNzb2NGaWxlLm0zdSIgQXBwbGljYXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBs
echo YXllciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5tNGEiIFByb2dJ
echo ZD0iV01QMTEuQXNzb2NGaWxlLk00QSIgQXBwbGljYXRpb25OYW1lPSJXaW5kb3dz
echo IE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5t
echo NHYiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLk1QNCIgQXBwbGljYXRpb25OYW1l
echo PSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50
echo aWZpZXI9Ii5ta3YiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLk1LViIgQXBwbGlj
echo YXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0
echo aW9uIElkZW50aWZpZXI9Ii5tb2QiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLk1Q
echo RUciIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQog
echo IDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIubW92IiBQcm9nSWQ9IldNUDExLkFz
echo c29jRmlsZS5NT1YiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5
echo ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuTVAyIiBQcm9nSWQ9
echo IldNUDExLkFzc29jRmlsZS5NUDMiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBN
echo ZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIubXAz
echo IiBQcm9nSWQ9IldNUDExLkFzc29jRmlsZS5NUDMiIEFwcGxpY2F0aW9uTmFtZT0i
echo V2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlm
echo aWVyPSIubXA0IiBQcm9nSWQ9IldNUDExLkFzc29jRmlsZS5NUDQiIEFwcGxpY2F0
echo aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlv
echo biBJZGVudGlmaWVyPSIubXA0diIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuTVA0
echo IiBBcHBsaWNhdGlvbk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8
echo QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLm1wYSIgUHJvZ0lkPSJXTVAxMS5Bc3Nv
echo Y0ZpbGUuTVBFRyIgQXBwbGljYXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXll
echo ciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5NUEUiIFByb2dJZD0i
echo V01QMTEuQXNzb2NGaWxlLk1QRUciIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBN
echo ZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIubXBl
echo ZyIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuTVBFRyIgQXBwbGljYXRpb25OYW1l
echo PSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50
echo aWZpZXI9Ii5tcGciIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLk1QRUciIEFwcGxp
echo Y2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lh
echo dGlvbiBJZGVudGlmaWVyPSIubXB2MiIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUu
echo TVBFRyIgQXBwbGljYXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4N
echo CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5tdHMiIFByb2dJZD0iV01QMTEu
echo QXNzb2NGaWxlLk0yVFMiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQ
echo bGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIucG5nIiBQcm9n
echo SWQ9IlBCcnVzaCIgQXBwbGljYXRpb25OYW1lPSJQYWludCIgLz4NCiAgPEFzc29j
echo aWF0aW9uIElkZW50aWZpZXI9Ii50aWYiIFByb2dJZD0iUGhvdG9WaWV3ZXIuRmls
echo ZUFzc29jLlRpZmYiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBQaG90byBWaWV3
echo ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIudGlmZiIgUHJvZ0lk
echo PSJQaG90b1ZpZXdlci5GaWxlQXNzb2MuVGlmZiIgQXBwbGljYXRpb25OYW1lPSJX
echo aW5kb3dzIFBob3RvIFZpZXdlciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50aWZp
echo ZXI9Ii5UUyIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuVFRTIiBBcHBsaWNhdGlv
echo bk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8QXNzb2NpYXRpb24g
echo SWRlbnRpZmllcj0iLlRUUyIgUHJvZ0lkPSJXTVAxMS5Bc3NvY0ZpbGUuVFRTIiBB
echo cHBsaWNhdGlvbk5hbWU9IldpbmRvd3MgTWVkaWEgUGxheWVyIiAvPg0KICA8QXNz
echo b2NpYXRpb24gSWRlbnRpZmllcj0iLnR4dCIgUHJvZ0lkPSJ0eHRmaWxlIiBBcHBs
echo aWNhdGlvbk5hbWU9Ik5vdGVwYWQiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlm
echo aWVyPSIudXJsIiBQcm9nSWQ9IklFLkFzc29jRmlsZS5VUkwiIEFwcGxpY2F0aW9u
echo TmFtZT0iSW50ZXJuZXQgQnJvd3NlciIgLz4NCiAgPEFzc29jaWF0aW9uIElkZW50
echo aWZpZXI9Ii53YXYiIFByb2dJZD0iV01QMTEuQXNzb2NGaWxlLldBViIgQXBwbGlj
echo YXRpb25OYW1lPSJXaW5kb3dzIE1lZGlhIFBsYXllciIgLz4NCiAgPEFzc29jaWF0
echo aW9uIElkZW50aWZpZXI9Ii53ZWJzaXRlIiBQcm9nSWQ9IklFLkFzc29jRmlsZS5X
echo RUJTSVRFIiBBcHBsaWNhdGlvbk5hbWU9IkludGVybmV0IEV4cGxvcmVyIiAvPg0K
echo ICA8QXNzb2NpYXRpb24gSWRlbnRpZmllcj0iLndtIiBQcm9nSWQ9IldNUDExLkFz
echo c29jRmlsZS5BU0YiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5
echo ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIud21hIiBQcm9nSWQ9
echo IldNUDExLkFzc29jRmlsZS5XTUEiIEFwcGxpY2F0aW9uTmFtZT0iV2luZG93cyBN
echo ZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIud212
echo IiBQcm9nSWQ9IldNUDExLkFzc29jRmlsZS5XTVYiIEFwcGxpY2F0aW9uTmFtZT0i
echo V2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVudGlm
echo aWVyPSIuV1BMIiBQcm9nSWQ9IldNUDExLkFzc29jRmlsZS5XUEwiIEFwcGxpY2F0
echo aW9uTmFtZT0iV2luZG93cyBNZWRpYSBQbGF5ZXIiIC8+DQogIDxBc3NvY2lhdGlv
echo biBJZGVudGlmaWVyPSJodHRwIiBQcm9nSWQ9IklFLkhUVFAiIEFwcGxpY2F0aW9u
echo TmFtZT0iSW50ZXJuZXQgRXhwbG9yZXIiIC8+DQogIDxBc3NvY2lhdGlvbiBJZGVu
echo dGlmaWVyPSJodHRwcyIgUHJvZ0lkPSJJRS5IVFRQUyIgQXBwbGljYXRpb25OYW1l
echo PSJJbnRlcm5ldCBFeHBsb3JlciIgLz4NCjwvRGVmYXVsdEFzc29jaWF0aW9ucz4N
echo Cg==
) > %_b64%

cls
certutil -decode %_b64% %_xml% > nul & del %_b64%
if not exist %_file% exit
dism /English /LogLevel:1 /Image:%_mnt% /Import-DefaultAppAssociations:%_xml%
if %ERRORLEVEL% NEQ 0 set _make=Discard & pause
del %_xml%

cls
dism /English /LogLevel:1 /Unmount-Image /MountDir:%_mnt% /%_make%
if %ERRORLEVEL% NEQ 0 pause
rd %_mnt%
